
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'vim-denops/denops.vim'

#python
[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

#ddc.vim
[[plugins]]
repo = 'Shougo/ddc.vim'

[[plugins]]
repo = 'Shougo/pum.vim'

[[plugins]]
repo = 'matsui54/denops-signature_help'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'

#filter
[[plugins]]
repo = 'tani/ddc-fuzzy'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'

#source
[[plugins]]
repo = 'shun/ddc-vim-lsp'

[[plugins]]
repo = 'Shougo/ddc-around'
