alias vz='vim ~/.zshrc'
alias vv='vim ~/.vimrc'
alias vtoml='vim ~/.vim/dein/dein.toml'
alias sz='source ~/.zshrc'
alias nheader='norminette -R CheckForbiddenSourceHeader'
alias Wgcc='gcc -Wall -Wextra -Werror'
alias ....='cd ../../../'
alias ...='cd ../../'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gcm='git commit -m'
alias gp='git push'
alias fa='find . -type f|sort|grep ex0'
alias l='ls --color=auto'
alias ls='ls --color=auto'
alias la='ls -la --color=auto'
alias ll='ls -l --color=auto'
alias lR='ls -R --color=auto'
alias vp='vim -p'
alias v='vim'
alias m='make'
alias c='clear'
alias grep='grep --color=auto'
alias -g C='| clip.exe'
alias -g G='| grep --color=auto'
alias -g L='| less'
alias -g VR='>result && view result'
